package bl_biblioteca.visao;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import bl_biblioteca.controle.ConectaBanco;
import bl_biblioteca.controle.ControleEmprestimo;
import bl_biblioteca.controle.ControleExemplar;
import bl_biblioteca.controle.ControleLivro;
import bl_biblioteca.modelo.ModeloEmprestimo;
import bl_biblioteca.modelo.ModeloLivro;

public class JDBaixa extends javax.swing.JDialog {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conectaExemplar = new ConectaBanco();
    ConectaBanco conectaEmprestimo = new ConectaBanco();
    ModeloEmprestimo modEmprestimo = new ModeloEmprestimo();
    ControleEmprestimo controlEmprestimo = new ControleEmprestimo();
    ModeloLivro modLivro = new ModeloLivro();
    ControleExemplar controlExemplar = new ControleExemplar();
    //Variaveis para controle dos botões
    boolean registroLivro = false;

    public JDBaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conecta.conexao();
        conectaEmprestimo.conexao();
        conectaExemplar.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonEfetuarBaixa = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRegistroLivro = new bl_biblioteca.controle.ControleJtextFieldNumeros(8);
        jLabel2 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTituloLivro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldArea = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVolume = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSerie = new javax.swing.JTextField();
        jTextFieldEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPublicacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Efetuar Baixa");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonEfetuarBaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEfetuarBaixa.setText("Confirmar");
        jButtonEfetuarBaixa.setEnabled(false);
        jButtonEfetuarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEfetuarBaixaActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Registro:");

        jTextFieldRegistroLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldRegistroLivro.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Informe o registro do livro para ser retirado do acervo:");

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Título:");

        jTextFieldTituloLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTituloLivro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTituloLivro.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Área:");

        jTextFieldArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldArea.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Autor:");

        jTextFieldAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldAutor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAutor.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Volume:");

        jTextFieldVolume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldVolume.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldVolume.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Série:");

        jTextFieldSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldSerie.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSerie.setEnabled(false);

        jTextFieldEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEntrada.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEntrada.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Entrada:");

        jTextFieldEditora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEditora.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEditora.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Editora:");

        jTextFieldPublicacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPublicacao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPublicacao.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Publicação:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonCancelar)
                            .addGap(37, 37, 37)
                            .addComponent(jButtonEfetuarBaixa))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldRegistroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonBuscar))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel7))
                                                    .addGap(4, 4, 4))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jTextFieldEntrada)
                                                    .addGap(53, 53, 53)
                                                    .addComponent(jLabel5)))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldVolume, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                                .addComponent(jTextFieldSerie)
                                                .addComponent(jTextFieldPublicacao))))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegistroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEfetuarBaixa)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEfetuarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfetuarBaixaActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja efetuar a baixa do registro informado? ", "Confirmação de baixa", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            modEmprestimo.setExemplar(Integer.parseInt(jTextFieldRegistroLivro.getText()));
            controlExemplar.efetuarBaixa(modEmprestimo);
            jButtonEfetuarBaixa.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jTextFieldRegistroLivro.setEnabled(true);
            jTextFieldRegistroLivro.setText("");
            limparInfoLivros();
            jButtonBuscar.setEnabled(true);
        } else {
            jButtonEfetuarBaixa.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jTextFieldRegistroLivro.setEnabled(true);
            jTextFieldRegistroLivro.setText("");
            limparInfoLivros();
            jButtonBuscar.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonEfetuarBaixaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jButtonEfetuarBaixa.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jTextFieldRegistroLivro.setEnabled(true);
        jTextFieldRegistroLivro.setText("");
        jTextFieldTituloLivro.setText("");
        jButtonBuscar.setEnabled(true);
        limparInfoLivros();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarExemplar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    public void buscarExemplar() { // Verifica se o numero informado corresponde a um registro de livro
        if (jTextFieldRegistroLivro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo(s) vazios!");
            jButtonBuscar.setEnabled(true);
        } else {

            try {
                PreparedStatement pstExemplar;  //Este trecho realiza consulta tabela livro, verificando se o registro existe
                pstExemplar = conectaExemplar.conn.prepareStatement("SELECT livro.titulo as titulo, autor.nome as autor, area.nome as area,  livro.volume as volume, \n"
                        + "livro.serie as serie, to_char (exemplar.data_entrada, 'dd/mm/yyyy ')  as entrada, editora.nome as editora, livro.ano_publicacao as publicacao\n"
                        + "FROM single.livro as livro\n"
                        + "INNER JOIN single.exemplar as exemplar\n"
                        + "on exemplar.livro = livro.registro\n"
                        + "inner join single.area as area\n"
                        + "on area.codigo = livro.area\n"
                        + "inner join single.autor as autor\n"
                        + "on autor.codigo = livro.autor\n"
                        + "inner join single.editora editora\n"
                        + "on editora.codigo = livro.editora\n"
                        + "where exemplar.registro = ? \n"
                        + "and data_saida is null");
                pstExemplar.setInt(1, Integer.parseInt(jTextFieldRegistroLivro.getText()));
                pstExemplar.execute();
                ResultSet rsLivro = pstExemplar.getResultSet();
                if (rsLivro.next()) {
                    jTextFieldTituloLivro.setText(rsLivro.getString("titulo"));
                    jTextFieldAutor.setText(rsLivro.getString("autor"));
                    jTextFieldArea.setText(rsLivro.getString("area"));
                    jTextFieldSerie.setText(rsLivro.getString("serie"));
                    jTextFieldVolume.setText(rsLivro.getString("volume"));
                    jTextFieldEntrada.setText(rsLivro.getString("entrada"));
                    jTextFieldEditora.setText(rsLivro.getString("editora"));
                    jTextFieldPublicacao.setText(rsLivro.getString("publicacao"));
                    registroLivro = true;

                    if ((registroLivro == true)) {
                        consultarEmprestimo();
                    }
                } else {
                    limparInfoLivros();
                    JOptionPane.showMessageDialog(null, "O número do registro informado não existe na base de dados."
                                                        + "\n Por favor verifique se registro digitado está correto!");
                    jButtonCancelar.setEnabled(true);
                }
            } catch (SQLException ex) {
            }
        }
    }

    public void consultarEmprestimo() { // Verifica se o livro esta emprestado ou não
        try {
            PreparedStatement pstEmprestimo;
            pstEmprestimo = conectaEmprestimo.conn.prepareStatement("select * from single.emprestimo where exemplar = ? order by codigo desc limit 1");
            pstEmprestimo.setInt(1, Integer.parseInt(jTextFieldRegistroLivro.getText()));
            pstEmprestimo.execute();
            ResultSet rsItem = pstEmprestimo.getResultSet();
            Boolean emprestado;
            if (rsItem.next()) {
                emprestado = rsItem.getBoolean("status");
                if (emprestado == true) {
                    limparInfoLivros();
                    JOptionPane.showMessageDialog(null, "O registro informado refere-se,"
                            + " a um livro emprestado. "
                            + "\nPor favor verifique se registro digitado está correto, ou efetue a devolução deste livro");
                    jButtonCancelar.setEnabled(false);
                    jTextFieldRegistroLivro.setEnabled(true);
                    jButtonEfetuarBaixa.setEnabled(false);
                } else {
                    jButtonEfetuarBaixa.setEnabled(true);
                    jButtonCancelar.setEnabled(true);
                    jButtonBuscar.setEnabled(false);
                    jTextFieldRegistroLivro.setEnabled(false);
                }
            } else {
                jButtonEfetuarBaixa.setEnabled(true);
                jButtonCancelar.setEnabled(true);
                jButtonBuscar.setEnabled(false);
                jTextFieldRegistroLivro.setEnabled(false);
            }
        } catch (SQLException ex) {
        }
    }

    public void limparInfoLivros() {
        jTextFieldTituloLivro.setText("");
        jTextFieldSerie.setText("");
        jTextFieldVolume.setText("");
        jTextFieldAutor.setText("");
        jTextFieldArea.setText("");
        jTextFieldEditora.setText("");
        jTextFieldEntrada.setText("");
        jTextFieldPublicacao.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDBaixa dialog = new JDBaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEfetuarBaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldEditora;
    private javax.swing.JTextField jTextFieldEntrada;
    private javax.swing.JTextField jTextFieldPublicacao;
    private javax.swing.JTextField jTextFieldRegistroLivro;
    private javax.swing.JTextField jTextFieldSerie;
    private javax.swing.JTextField jTextFieldTituloLivro;
    private javax.swing.JTextField jTextFieldVolume;
    // End of variables declaration//GEN-END:variables
}
