/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bl_biblioteca.visao;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import bl_biblioteca.controle.ConectaBanco;
import bl_biblioteca.controle.ControleEmprestimo;
import bl_biblioteca.modelo.ModeloEmprestimo;

public class JDDevolucao extends javax.swing.JDialog {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conectaEmprestimo = new ConectaBanco();
    ConectaBanco conectaLivro = new ConectaBanco();
    ModeloEmprestimo modEmprestimo = new ModeloEmprestimo();
    ControleEmprestimo controlEmprestimo = new ControleEmprestimo();
    //Variaveis para controle dos botões
    boolean registroLivro = false;

    public JDDevolucao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conecta.conexao();
        conectaLivro.conexao();
        conectaEmprestimo.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonDevolver = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRegistroLivro = new bl_biblioteca.controle.ControleJtextFieldNumeros(8);
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTituloLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonBuscarRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSerie = new javax.swing.JTextField();
        jTextFieldArea = new javax.swing.JTextField();
        jTextFieldVolume = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAtendente = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Efetuar Devolução");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonDevolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDevolver.setText("Devolver");
        jButtonDevolver.setEnabled(false);
        jButtonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Registro:");

        jTextFieldRegistroLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldRegistroLivro.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Informe o registro do livro que será devolvido:");

        jTextFieldTituloLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTituloLivro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTituloLivro.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Título:");

        jButtonBuscarRegistro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuscarRegistro.setText("Buscar");
        jButtonBuscarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarRegistroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Área:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Volume:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Série:");

        jTextFieldSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldSerie.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSerie.setEnabled(false);

        jTextFieldArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldArea.setEnabled(false);

        jTextFieldVolume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldVolume.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldVolume.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Atendente:");

        jTextFieldAtendente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldAtendente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAtendente.setEnabled(false);

        jTextFieldHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldHora.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldHora.setEnabled(false);
        jTextFieldHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Horário:");

        jTextFieldUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldUsuario.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldRegistroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonBuscarRegistro))
                                        .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jButtonCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonDevolver))
                                    .addComponent(jTextFieldHora, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(165, 165, 165))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegistroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonBuscarRegistro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonDevolver))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja efetuar a devolução do exemplar informado?", "Confirmação de devolução", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            modEmprestimo.setExemplar(Integer.parseInt(jTextFieldRegistroLivro.getText()));
            controlEmprestimo.devolverExemplar(modEmprestimo);
            jButtonDevolver.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jTextFieldRegistroLivro.setEnabled(true);
            jTextFieldRegistroLivro.setText("");
            jButtonBuscarRegistro.setEnabled(true);
            limparInfoLivros();
        } else {
            jButtonDevolver.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jTextFieldRegistroLivro.setEnabled(true);
            jTextFieldRegistroLivro.setText("");
            limparInfoLivros();
            jButtonBuscarRegistro.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonDevolverActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jButtonDevolver.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jTextFieldRegistroLivro.setEnabled(true);
        jTextFieldRegistroLivro.setText("");
        limparInfoLivros();
        jButtonBuscarRegistro.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarRegistroActionPerformed
        buscarExemplar();
    }//GEN-LAST:event_jButtonBuscarRegistroActionPerformed

    private void jTextFieldHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraActionPerformed

    public void buscarExemplar() { // Verifica se o numero informado corresponde a um registro de livro
        if (jTextFieldRegistroLivro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo(s) vazios!");
            jButtonBuscarRegistro.setEnabled(true);
        } else {

            try {
                PreparedStatement pstExemplar;  //Este trecho realiza consulta tabela livro, verificando se o registro existe
                //           pstExemplar = conectaLivro.conn.prepareStatement("SELECT * FROM single.exemplar where registro=? and data_saida is null");
                pstExemplar = conectaLivro.conn.prepareStatement("SELECT exemplar.registro as registro, livro.titulo as titulo, area.nome as area, livro.volume, livro.serie, to_char (exemplar.data_entrada, 'dd/mm/yyyy')  as entrada\n"
                        + "FROM single.emprestimo\n"
                        + "inner join single.exemplar exemplar\n"
                        + "on emprestimo.exemplar = exemplar.registro\n"
                        + "inner join single.livro livro\n"
                        + "on livro.registro = exemplar.livro\n"
                        + "inner join single.area area\n"
                        + "on area.codigo = livro.area\n"
                        + "inner join single.autor autor\n"
                        + "on autor.codigo = livro.autor\n"
                        + "where exemplar.registro=? and data_saida is null");
                pstExemplar.setInt(1, Integer.parseInt(jTextFieldRegistroLivro.getText()));
                pstExemplar.execute();
                ResultSet rsExemplar = pstExemplar.getResultSet();
                if (rsExemplar.next()) {
                    // Titulo, area, volume, serie, atendente, hora
                    jTextFieldTituloLivro.setText(rsExemplar.getString("titulo"));
                    jTextFieldArea.setText(rsExemplar.getString("area"));
                    jTextFieldSerie.setText(rsExemplar.getString("serie"));
                    jTextFieldVolume.setText(rsExemplar.getString("volume"));
                    registroLivro = true;
                } else {
                    limparInfoLivros();
                    JOptionPane.showMessageDialog(null, "O número do registro informado "
                            + "pertence a um livro disponível para emprestimo "
                            + "\n ou não existe"
                            + " na base de dados."
                            + "\n Por favor verifique se registro digitado está correto!");
                    jButtonCancelar.setEnabled(true);
                }
                if ((registroLivro == true)) {
                    consultarEmprestimo();
                }
            } catch (SQLException ex) {
            }
        }
    }

    public void consultarEmprestimo() { // Verifica se o livro esta emprestado ou não
        try {
            PreparedStatement pstEmprestimo;
         //   pstEmprestimo = conectaEmprestimo.conn.prepareStatement("select * from single.emprestimo, single.atendente where exemplar = ? order by codigo desc limit 1");
            pstEmprestimo = conectaEmprestimo.conn.prepareStatement("select atendente.nome as nome, to_char (emprestimo.data_hora, 'dd/mm/yyyy HH24:MI:SS') as hora, users.name as usuario, emprestimo.status as status\n" +
                                                                    "from single.emprestimo emprestimo\n" +
                                                                    "inner join single.atendente atendente\n" +
                                                                    "on emprestimo.atendente = atendente.id\n" +
                                                                    "inner join single.users users\n" +
                                                                    "on users.id = emprestimo.users\n" +
                                                                    "where emprestimo.exemplar = ? \n" +
                                                                    "order by codigo desc limit 1");
            pstEmprestimo.setInt(1, Integer.parseInt(jTextFieldRegistroLivro.getText()));
            pstEmprestimo.execute();
            ResultSet rsItem = pstEmprestimo.getResultSet();
            Boolean emprestado = null;

            if (rsItem.next()) {
                emprestado = rsItem.getBoolean("status");
                if (emprestado == true) {
                    jButtonDevolver.setEnabled(true);
                    jButtonBuscarRegistro.setEnabled(false);
                    jTextFieldRegistroLivro.setEnabled(false);
                    jTextFieldAtendente.setText(rsItem.getString("nome"));
                    jTextFieldUsuario.setText(rsItem.getString("usuario"));
                    jTextFieldHora.setText(rsItem.getString("hora"));

                } else {
                    jButtonDevolver.setEnabled(false);
                    limparInfoLivros();
                    JOptionPane.showMessageDialog(null, "O registro informado, pertence a um livro disponível para empréstimo."
                            + "\n Por favor verifique se registro digitado está correto!, ou efetue a devolução do livro");
                }
            } else {
                jButtonDevolver.setEnabled(false);
                limparInfoLivros();
           //     JOptionPane.showMessageDialog(null, "O registro informado, pertence a um livro disponível para empréstimo."
           //             + "\n Por favor verifique se registro digitado está correto!, ou efetue a devolução do livro");
            }
        } catch (SQLException ex) {
        }
    }

    public void limparInfoLivros() {
        jTextFieldTituloLivro.setText("");
        jTextFieldSerie.setText("");
        jTextFieldVolume.setText("");
        jTextFieldAtendente.setText("");
        jTextFieldArea.setText("");
        jTextFieldHora.setText("");
        jTextFieldUsuario.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDDevolucao dialog = new JDDevolucao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarRegistro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldAtendente;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldRegistroLivro;
    private javax.swing.JTextField jTextFieldSerie;
    private javax.swing.JTextField jTextFieldTituloLivro;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JTextField jTextFieldVolume;
    // End of variables declaration//GEN-END:variables
}
