/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bl_biblioteca.visao;

import bl_biblioteca.controle.ConectaBanco;
import bl_biblioteca.controle.ControleEmprestimo;
import bl_biblioteca.modelo.ModeloAtendente;
import bl_biblioteca.modelo.ModeloEmprestimo;
import bl_biblioteca.modelo.ModeloTabela;
import bl_biblioteca.visao.FrmPrincipal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class JDEmprestimo extends javax.swing.JDialog {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conectaUsers = new ConectaBanco();
    ConectaBanco conectaEmprestimo = new ConectaBanco();
    ConectaBanco conectaLivro = new ConectaBanco();
    ModeloEmprestimo modEmprestimo = new ModeloEmprestimo();
    ModeloAtendente atendente = new ModeloAtendente();
    ControleEmprestimo controlEmprestimo = new ControleEmprestimo();
    //Variaveis para controle dos botões
    boolean codigoAluno = false;
    boolean registroLivro = false;
    public int idAtendente;

    public JDEmprestimo(java.awt.Frame parent, boolean modal, ModeloAtendente atendente1) {
        super(parent, modal);
        initComponents();
        conecta.conexao();
        conectaUsers.conexao();
        conectaLivro.conexao();
        conectaEmprestimo.conexao();
        // Pega o valor obj passado por parametro atendente1 e manda para o objeto atendente
        atendente.setId(atendente1.getId());
        limparTela();
        //preencherTabela("SELECT users.id, users.name ,livro.registro ,livro.titulo,livro.serie FROM single.users users , single.emprestimo emprestimo, single.item item, single.livro livro where users.id = emprestimo.users and	emprestimo.item = item.codigo and	item.livro = livro.registro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoAluno = new bl_biblioteca.controle.ControleJtextFieldNumeros(8);
        jButtonBuscarAluno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmprestimo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRegistroLivro = new bl_biblioteca.controle.ControleJtextFieldNumeros(8);
        jButtonBuscarRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTituloLivro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVolume = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSerie = new javax.swing.JTextField();
        jTextFieldArea = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEmprestar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar empréstimo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Informe o código do aluno:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Código:");

        jTextFieldCodigoAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCodigoAluno.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButtonBuscarAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuscarAluno.setText("Buscar");
        jButtonBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAlunoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNome.setEnabled(false);

        jTableEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTableEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableEmprestimo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscarAluno))
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 43, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarAluno)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Informe um número de registro:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Registro:");

        jTextFieldRegistroLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldRegistroLivro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldRegistroLivro.setEnabled(false);

        jButtonBuscarRegistro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuscarRegistro.setText("Buscar");
        jButtonBuscarRegistro.setEnabled(false);
        jButtonBuscarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarRegistroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Título:");

        jTextFieldTituloLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTituloLivro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTituloLivro.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Autor:");

        jTextFieldAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldAutor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAutor.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Volume:");

        jTextFieldVolume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldVolume.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldVolume.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Série:");

        jTextFieldSerie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldSerie.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSerie.setEnabled(false);

        jTextFieldArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldArea.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Área:");

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEmprestar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEmprestar.setText("Emprestar");
        jButtonEmprestar.setEnabled(false);
        jButtonEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmprestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jTextFieldRegistroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonBuscarRegistro))
                                        .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldSerie)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jButtonCancelar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonEmprestar))))))
                            .addComponent(jLabel4))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldRegistroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarRegistro))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEmprestar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAlunoActionPerformed
        buscarAluno();
    }//GEN-LAST:event_jButtonBuscarAlunoActionPerformed

    private void jButtonEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmprestarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja efetuar o empréstimo do livro exemplar informado?", "Confirmação de empréstimo", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            modEmprestimo.setAtendente(atendente.getId());
            modEmprestimo.setUsers(Integer.parseInt(jTextFieldCodigoAluno.getText()));
            modEmprestimo.setExemplar(Integer.parseInt(jTextFieldRegistroLivro.getText()));
            controlEmprestimo.realizarEmprestimo(modEmprestimo);
            jButtonCancelar.setEnabled(false);
            limparTela();
        } else {
            jButtonCancelar.setEnabled(false);
            limparTela();
        }
    }//GEN-LAST:event_jButtonEmprestarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparTela();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarRegistroActionPerformed
        buscarExemplar();
    }//GEN-LAST:event_jButtonBuscarRegistroActionPerformed

    public void buscarAluno() {

        if (jTextFieldCodigoAluno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo vazio!");
        } else {
            try {
                PreparedStatement pst;  //Este trecho realiza consulta tabela usuarios, verificando se o id existe
                pst = conectaUsers.conn.prepareStatement("select * from single.users where id=?");
                pst.setInt(1, Integer.parseInt(jTextFieldCodigoAluno.getText()));
                pst.execute();
                ResultSet rs = pst.getResultSet();

                if (rs.next()) {
                    jTextFieldNome.setText(rs.getString("name"));
                    codigoAluno = true;
                    int temp = rs.getInt("id");
                    preencherTabela("SELECT exemplar.registro as exemplar, livro.titulo as titulo, area.nome as area,  livro.volume as volume, \n"
                            + "livro.serie as serie, atendente.nome as atendente, to_char (emprestimo.data_hora, 'dd/mm/yyyy HH24:MI:SS ')  as hora\n"
                            + "FROM single.livro as livro\n"
                            + "INNER JOIN single.exemplar as exemplar\n"
                            + "on exemplar.livro = livro.registro\n"
                            + "inner join single.emprestimo as emprestimo\n"
                            + "on emprestimo.exemplar = exemplar.registro\n"
                            + "inner join single.atendente as atendente\n"
                            + "on emprestimo.atendente = atendente.id\n"
                            + "inner join single.users as users\n"
                            + "on users.id = emprestimo.users\n"
                            + "inner join single.area as area\n"
                            + "on area.codigo = livro.area\n"
                            + "where emprestimo.users = " + temp + "\n"
                            + "and emprestimo.status = true\n"
                            + "order by emprestimo.data_hora desc");
                    jButtonBuscarRegistro.setEnabled(true);
                    jButtonBuscarAluno.setEnabled(false);
                    jTextFieldCodigoAluno.setEnabled(false);
                    jTextFieldRegistroLivro.setEnabled(true);
                    jButtonCancelar.setEnabled(true);

                } else {
                    JOptionPane.showMessageDialog(null, "O código informado não existe na base de dados."
                            + "\n Por favor verifique se o código digitado está correto!");
                }
            } catch (SQLException ex) {
            }
        }
    }

    public void buscarExemplar() { // Verifica se o numero informado corresponde a um registro de livro,ATENÇAO LIVROS EM BAIXA NÃO SÃO EXIBIDOS (NÃO FAZEM PARTE DO ACERVO)
        if (jTextFieldRegistroLivro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo vazio!");
        } else {

            try {
                PreparedStatement pstExemplar;  //Este trecho realiza consulta tabela livro, verificando se o registro existe
                pstExemplar = conectaLivro.conn.prepareStatement("SELECT livro.titulo as titulo, autor.nome as autor, area.nome as area, livro.serie as serie, livro.volume as volume FROM single.exemplar exemplar\n"
                        + "inner join single.livro livro\n"
                        + "on exemplar.livro = livro.registro\n"
                        + "inner join single.area area\n"
                        + "on area.codigo = livro.area\n"
                        + "inner join single.autor autor\n"
                        + "on autor.codigo = livro.autor\n"
                        + " where exemplar.registro = ? and data_saida is null");
                pstExemplar.setInt(1, Integer.parseInt(jTextFieldRegistroLivro.getText()));
                pstExemplar.execute();
                ResultSet rsExemplar = pstExemplar.getResultSet();
                if (rsExemplar.next()) {
                    jTextFieldArea.setText(rsExemplar.getString("area"));
                    jTextFieldTituloLivro.setText(rsExemplar.getString("titulo"));
                    jTextFieldSerie.setText(rsExemplar.getString("serie"));
                    jTextFieldVolume.setText(rsExemplar.getString("volume"));
                    jTextFieldAutor.setText(rsExemplar.getString("autor"));
                    registroLivro = true;

                    if ((registroLivro == true) && (codigoAluno == true)) {
                        consultarEmprestimo();
                    }
                } else {
                    limparInfoLivros();
                    JOptionPane.showMessageDialog(null, "O registro informado não existe na base de dados."
                            + "\n Por favor verifique se registro digitado está correto!");
                }
            } catch (SQLException ex) {
            }
        }
    }

    public void consultarEmprestimo() { // Verifica se o livro esta emprestado ou não
        try {
            PreparedStatement pstEmprestimo;
            pstEmprestimo = conectaEmprestimo.conn.prepareStatement("select * from single.emprestimo where exemplar = ? order by codigo desc limit 1");
            pstEmprestimo.setInt(1, Integer.parseInt(jTextFieldRegistroLivro.getText()));
            pstEmprestimo.execute();
            ResultSet rsItem = pstEmprestimo.getResultSet();
            Boolean emprestado = null;

            if (rsItem.next()) {
                emprestado = rsItem.getBoolean("status");
                if (emprestado == true) {
                    jButtonEmprestar.setEnabled(false);
                    limparInfoLivros();
                    JOptionPane.showMessageDialog(null, "O registro informado, pertence a um livro já emprestado."
                            + "\n Por favor verifique se registro digitado está correto!");
                } else {
                    jButtonEmprestar.setEnabled(true);
                    jButtonBuscarRegistro.setEnabled(false);
                    jTextFieldRegistroLivro.setEnabled(false);
                }
            } else {
                jButtonEmprestar.setEnabled(true);
                jButtonBuscarRegistro.setEnabled(false);
                jTextFieldRegistroLivro.setEnabled(false);
            }
        } catch (SQLException ex) {
        }
    }

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Registro", "Título", "Área", "Volume", "Série", "Atendente", "Hora"};

        conecta.executaSQL(sql);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("exemplar"),
                    conecta.rs.getString("titulo"),
                    conecta.rs.getString("area"),
                    conecta.rs.getInt("volume"),
                    conecta.rs.getInt("serie"),
                    conecta.rs.getString("atendente"),
                    conecta.rs.getString("hora")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            // MSG DE ERRO COMENTADA 
            // CASO OCORRA A BUSCA DE UMA TABELA VAZIA, NAO APARECE MSG DE ERRO PARA O USUARIO
            // JOptionPane.showMessageDialog(rootPane, "Erro ao exibir tabela! \n ERRO:" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableEmprestimo.setModel(modelo);
        jTableEmprestimo.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableEmprestimo.getColumnModel().getColumn(0).setResizable(true);
        jTableEmprestimo.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableEmprestimo.getColumnModel().getColumn(1).setResizable(true);
        jTableEmprestimo.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTableEmprestimo.getColumnModel().getColumn(2).setResizable(true);
        jTableEmprestimo.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTableEmprestimo.getColumnModel().getColumn(3).setResizable(true);
        jTableEmprestimo.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTableEmprestimo.getColumnModel().getColumn(4).setResizable(true);
        jTableEmprestimo.getColumnModel().getColumn(5).setPreferredWidth(105);
        jTableEmprestimo.getColumnModel().getColumn(5).setResizable(true);
        jTableEmprestimo.getColumnModel().getColumn(6).setPreferredWidth(107);
        jTableEmprestimo.getColumnModel().getColumn(6).setResizable(true);
        jTableEmprestimo.getTableHeader().setReorderingAllowed(false);
        //jTableEmprestimo.setAutoResizeMode(jTableEmprestimo.AUTO_RESIZE_OFF);
        jTableEmprestimo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void limparTela() {
        jButtonBuscarRegistro.setEnabled(false);
        jButtonEmprestar.setEnabled(false);
        jButtonBuscarAluno.setEnabled(true);
        jTextFieldCodigoAluno.setText("");
        jTextFieldCodigoAluno.setEnabled(true);
        jTextFieldNome.setText("");
        jTextFieldTituloLivro.setText("");
        jTextFieldRegistroLivro.setText("");
        jTextFieldRegistroLivro.setEnabled(false);

        jTextFieldTituloLivro.setText("");
        jTextFieldSerie.setText("");
        jTextFieldVolume.setText("");
        jTextFieldAutor.setText("");
        jTextFieldArea.setText("");

        preencherTabela("SELECT users.id, users.name ,livro.registro ,livro.titulo,livro.serie \n"
                + "FROM single.users users , single.emprestimo emprestimo, single.exemplar exemplar, single.livro livro\n"
                + "where users.id  =" + 0 + " and users.id = emprestimo.users and emprestimo.exemplar = exemplar.registro and exemplar.livro = livro.registro");
    }

    public void limparInfoLivros() {
        jTextFieldTituloLivro.setText("");
        jTextFieldSerie.setText("");
        jTextFieldVolume.setText("");
        jTextFieldAutor.setText("");
        jTextFieldArea.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDEmprestimo dialog = new JDEmprestimo(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarAluno;
    private javax.swing.JButton jButtonBuscarRegistro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEmprestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmprestimo;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCodigoAluno;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRegistroLivro;
    private javax.swing.JTextField jTextFieldSerie;
    private javax.swing.JTextField jTextFieldTituloLivro;
    private javax.swing.JTextField jTextFieldVolume;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the idAtendente
     */
    public int getIdAtendente() {
        return idAtendente;
    }

    /**
     * @param idAtendente the idAtendente to set
     */
    public void setIdAtendente(int idAtendente) {
        this.idAtendente = idAtendente;
    }
}
