/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bl_biblioteca.visao;


import bl_biblioteca.controle.ConectaBanco;
import bl_biblioteca.controle.ControleJtextFieldSomenteLetras;
import bl_biblioteca.controle.ControleJtextFieldStrings;
import bl_biblioteca.controle.ControleLocal;
import bl_biblioteca.modelo.ModeloTabela;
import bl_biblioteca.modelo.ModeloLocal;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Diego
 */
public class JDLocal extends javax.swing.JDialog {

    ConectaBanco conecta = new ConectaBanco();
    ModeloLocal mod = new ModeloLocal();
    ControleLocal controlLocal = new ControleLocal();

    public JDLocal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         initComponents();
        conecta.conexao();
        preencherTabela("select * from single.local order by codigo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCidade = new ControleJtextFieldStrings(50);
        jTextFieldEstado = new ControleJtextFieldSomenteLetras(2);
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLocal = new javax.swing.JTable();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar local");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cidade:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("UF:");

        jTextFieldCidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCidade.setEnabled(false);

        jTextFieldEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEstado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEstado.setEnabled(false);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir local");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar local");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Novo Local");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setToolTipText("Alterar local");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jTableLocal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTableLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableLocal);

        jButtonPrimeiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPrimeiro.setText("<<");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonUltimo.setText("<");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonAnterior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAnterior.setText(">");
        jButtonAnterior.setEnabled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonProximo.setText(">>");
        jButtonProximo.setEnabled(false);
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonExcluir))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonPrimeiro)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonUltimo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonAnterior)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonNovo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSalvar))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(533, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        /*        try {
         if ((jTextFieldEstado.getText().isEmpty())) {
         JOptionPane.showMessageDialog(rootPane, "Campo(s) vazios! Para excluir um registro é necessário informar a sigla do estado");
         } else {
         int opcao = JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja excluir este registro?");

         if (opcao == 0) {
         conecta.executaSQL("delete from single.local where estado_sigla ='" + jTextFieldEstado.getText() + "'");
         JOptionPane.showMessageDialog(rootPane, "Excluido com sucesso!");
         preencherTabela("select * from single.local order by codigo");
         }
         }
         } catch (Exception e) {
         }

         jTextFieldCidade.setText("");
         jTextFieldEstado.setText("");
         jTextFieldCidade.setEnabled(false);
         jTextFieldEstado.setEnabled(false);
         jTextFieldEstado.setEnabled(false);
         jButtonAlterar.setEnabled(false);
         jButtonExcluir.setEnabled(false);
         jButtonSalvar.setEnabled(false);
         jButtonNovo.setEnabled(true);
         *
         * Atenção este codigo esta excluido pela SIGLA, não pode pq um estado pode ter várias cidades
         */

        try {
            if (jTextFieldCidade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Campo vazio! Para excluir um registro é necessário informar a cidade");
            } else {
                mod.setCidade(jTextFieldCidade.getText());
                controlLocal.excluirLocal(mod);
                preencherTabela("select * from single.local order by codigo");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir! \n ERRO:" + e);
        }
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldEstado.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        /*     try {
         if ((jTextFieldCidade.getText().isEmpty()) || (jTextFieldEstado.getText().isEmpty())) {
         JOptionPane.showMessageDialog(rootPane, "Campo(s) vazios!");
         } else {
         PreparedStatement pst = conecta.conn.prepareStatement("insert into single.local (cidade , estado_sigla)values(?,?)");
         //pst.setString(numero do paramentro, nome do campo);
         pst.setString(1, jTextFieldCidade.getText());
         pst.setString(2, jTextFieldEstado.getText());
         pst.executeUpdate();
         JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");
         preencherTabela("select * from single.local order by codigo");
         }
         } catch (SQLException ex) {
         JOptionPane.showMessageDialog(rootPane, "Erro na inserção! A sigla do estado deve conter apenas dois caracteres \n ERRO:" + ex);
         }

         jTextFieldCidade.setText("");
         jTextFieldEstado.setText("");
         jTextFieldCidade.setEnabled(false);
         jTextFieldEstado.setEnabled(false);
         jButtonAlterar.setEnabled(false);
         jButtonExcluir.setEnabled(false);
         jButtonSalvar.setEnabled(false);
         jButtonNovo.setEnabled(true);
         */
        try {
            if ((jTextFieldCidade.getText().isEmpty())) {
                JOptionPane.showMessageDialog(rootPane, "Campo(s) vazios!");
            } else {
                mod.setCidade(jTextFieldCidade.getText());
                mod.setEstado_sigla(jTextFieldEstado.getText());
                controlLocal.inserirLocal(mod);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar! \n ERRO:" + e);
        }
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCidade.setEnabled(false);
        jTextFieldEstado.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        preencherTabela("select * from single.local order by codigo");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCidade.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        /*      try {
         PreparedStatement pst = conecta.conn.prepareStatement("update single.local set cidade = ?, estado_sigla=? where codigo = ? ");
         pst.setString(1, jTextFieldCidade.getText());
         pst.setString(2, jTextFieldEstado.getText());
         pst.setInt(3, Integer.parseInt(conecta.rs.getString("codigo")));
         pst.executeUpdate();
         JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
         preencherTabela("select * from single.local order by codigo");
         } catch (SQLException ex) {
         JOptionPane.showMessageDialog(rootPane, "Erro ao alterar! \n ERRO:" + ex);
         }
         */
        int codigo;
        try {
            // variavel armazena codigo da area que será alterada
            if (jTextFieldCidade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Campo vazio! Para alterar um registro é necessário informar o nome de uma cidade");
            } else {
                codigo = Integer.parseInt(conecta.rs.getString("codigo"));
                mod.setCidade(jTextFieldCidade.getText());
                mod.setCodigo(codigo);
                mod.setEstado_sigla(jTextFieldEstado.getText());
                controlLocal.alteraLocal(mod);
                preencherTabela("select * from single.local order by codigo");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao alterar! \n ERRO:" + e);
        }

        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCidade.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        jTextFieldCidade.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonProximo.setEnabled(true);
        jButtonAnterior.setEnabled(false);
        try {
            conecta.executaSQL("select * from single.local");
            conecta.rs.first();
            jTextFieldCidade.setText(conecta.rs.getString("cidade"));
            jTextFieldEstado.setText(conecta.rs.getString("estado_sigla"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados! \n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jButtonAnterior.setEnabled(true);

        try {
            conecta.executaSQL("select * from single.local");
            conecta.rs.last();
            jTextFieldEstado.setText(conecta.rs.getString("estado_sigla"));
            jTextFieldCidade.setText(conecta.rs.getString("cidade"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados! \n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jButtonProximo.setEnabled(true);

        try {
            if (!conecta.rs.previous()) {
                jButtonAnterior.setEnabled(false);
                return;
            }
            jTextFieldCidade.setText(conecta.rs.getString("cidade"));
            jTextFieldEstado.setText(conecta.rs.getString("estado_sigla"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados! \n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jButtonAnterior.setEnabled(true);

        try {
            if (!conecta.rs.next()) {
                jButtonProximo.setEnabled(false);
                return;
            }
            jTextFieldCidade.setText(conecta.rs.getString("cidade"));
            jTextFieldEstado.setText(conecta.rs.getString("estado_sigla"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir dados! \n ERRO:" + ex);
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

     public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Cidade", "Estado"};

        conecta.executaSQL(sql);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("codigo"), conecta.rs.getString("cidade"), conecta.rs.getString("estado_sigla")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao exibir tabela! \n ERRO:" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableLocal.setModel(modelo);
        jTableLocal.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableLocal.getColumnModel().getColumn(0).setResizable(false);
        jTableLocal.getColumnModel().getColumn(1).setPreferredWidth(266);
        jTableLocal.getColumnModel().getColumn(1).setResizable(false);
        jTableLocal.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTableLocal.getColumnModel().getColumn(2).setResizable(false);
        jTableLocal.getTableHeader().setReorderingAllowed(false);
        jTableLocal.setAutoResizeMode(jTableLocal.AUTO_RESIZE_OFF);
        jTableLocal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDLocal dialog = new JDLocal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLocal;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEstado;
    // End of variables declaration//GEN-END:variables
}
